# Generated by Django 2.2.14 on 2021-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='vibe.png', upload_to='profile_pics'),
        ),
    ]
