# Generated by Django 2.2.14 on 2021-11-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210606_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/vibe.png', upload_to='profile_pics'),
        ),
    ]
